### ISSUE TITLE
デザイン決め

### ISSUE THREAD

**Issue by afrou04** [tetsu-tech/hackathon-repo#4]
モックUIのままなのでデザインを作成する必要がある。

### 方針
- まずはマルパクリする
- パクった後にちょっとだけ色とかを変更する

### TODO
~~- [ ] XDか何かでUIを作成する。~~
- [x] ドロワーの変更
  - [ ] ドロワーのカラー変更
  - [ ] サービス名を入れる
  - [ ] 組織名を入れる
  - [ ] テンプレートの一覧を取得する
  - [ ] テンプレートの追加ボタン
  - [ ] テンプレートのアイコンとテンプレート名を入れる
- [x] テンプレート
  - [ ] テンプレート名の表示
  - [ ] テンプレートの削除
  - [ ] テンプレートの項目表示
- [x] テンプレートの追加
  - [ ] タイトル
  - [ ] 説明
  - [ ] テンプレートタイトル
  - [ ] テンプレートissue項目
  - [ ] キャンセル、作成ボタン
- [x] issueの追加
  - [ ] タイトル
  - [ ] 説明
  - [ ] テンプレートタイトル
  - [ ] テンプレートissue項目
  - [ ] キャンセル、作成ボタン

### 共通化UI
- ボタンは主に3種類

### やりたい
- [ ] テンプレートが1つもないときのUIを入れる
  - [ ] 画像、タイトル、テンプレートの追加ボタン

- [ ] ログアウトボタン
- [ ] デフォルトのslack連携UI追加

**Comment by TakuroSugahara** [comment]
![85B8B99E-57BD-4559-ACCE-4DE91B2A7EEE](https://user-images.githubusercontent.com/38108000/77387321-757d6a00-6dd0-11ea-84f7-e3a5728a5539.jpeg)

マルパします。

**Comment by TakuroSugahara** [comment]
<img width="1654" alt="スクリーンショット 2020-03-24 15 21 16" src="https://user-images.githubusercontent.com/38108000/77492184-3bb96b80-6e83-11ea-8f75-bb54e1b6f63e.png">
<img width="1662" alt="スクリーンショット 2020-03-24 15 21 25" src="https://user-images.githubusercontent.com/38108000/77492197-41af4c80-6e83-11ea-8c0c-46f817890652.png">

**Comment by afrou04** [comment]
てつおくんからもらったスクショからデザインを作る
